changes.go
changes_test.go
cmd/get-bundle-changes/main.go
handlers.go

A change is now expressed as an interface.
Avoid using []inteface{} for the arguments.
Define specific types for each change implementation instead.

More go-friendly representation for changes.

---

changes.go
changes_test.go
handlers.go

Specifically:
- handle service constraints;
- avoid passing the number of units (always 1) to addUnit GUIArgs;
- use a placeholder for the addService charm, pointing to the corresponding
addCharm change, to be replaced with the fully resolved charm id.
Note that this is a backward incompatible change and both juju-core and 
the Juju GUI will need to be updated.

bundlechanges: remove format inconsistencies.

---

changes.go
changes_test.go
cmd/get-bundle-changes/main.go
dependencies.tsv
handlers.go

Add support for storage constraints to bundle changes.
This will be used by juju/juju to deploy bundles with
services that require storage.
Storage constraints are being added to GUI arguments;
I'm not sure if this will have any negative effects,
or if extraneous arguments are simply ignored. Please
advise.

Add Storage to AddServiceParams

---

changes.go
changes_test.go
handlers.go

Addresses https://bugs.launchpad.net/juju-core/+bug/1564057 - will require a dependencies update in core.

Choose series for machines based on charm/default series

---

changes_test.go
dependencies.tsv
handlers.go

If the charm in a bundle is a local path, we need to allow for the fact that the charm may define a default series in metadata. We check for that first before trying to get the series from the charm url.

Bundle series selection supports charm default series

---

changes.go
changes_test.go
handlers.go

We add a Series attribute the the AddServiceParams. This is needed because the store charm URL may not contain a series and we need therefore to record any series specified in the bundle. This is the same as is done for AddCharmParams. The series is needed for both - it is used when the charm is added to Juju and when the service is deployed.

Record the service series in AddServiceParams

---

changes_test.go
handlers.go

Fixes bug #1626597 in Juju. Application constraints are added to the add machine changes for containers. 
There was an existing test asserting that this was *not done* as that was the previous specification. This is a specification change, so I have changed the existing test rather than needing to add a new one.

Put application constraints on container addMachine changes

---

changes_test.go
handlers.go

When deploying a large bundle containers can be deployed before units are assigned to them. This might cause them not to have required spaces assigned. This patch fixes it by setting an explicit constraint for spaces on machines deployed for applications.

Add endpoint spaces to machines constraints

---

changes_test.go
dependencies.tsv
handlers.go

Since the machine keys were being sorted alphabetically, the library would try to create machine 10 before machine 2.

Sort machines naturally.

---

changes.go
changes_test.go
cmd/get-bundle-changes/main.go
dependencies.tsv
handlers.go
model.go
model_test.go

This change introduces a number of things.
Firstly, the public interface is changed to also require a logger. The configuration struct also would be a good place to add charms for some charm resolution checks.
The infer machine map first looks to check machine placement before falling back to older algorithm.
When determing placement for new units when some are already placed, instead of indexing into the placement array, a value is popped off a list of unsatisfied placement directives.
The tests have also been refactored to remove the table based tests, which were hard to get through when things failed.

Smarter placement detection for rerunning bundles.

---

changes_test.go
model.go

The last commit effectively always had the behaviour of "--map-machines=existing" set. This branch reinstates the old behaviour.

Reinstate existing machine behaviour.

---

changes.go
changes_test.go

Note: this is `not` an ideal solution, but it avoids too much effort here to introduce proper versioning of changes.

added GUIArgsLegacy for backward support GUI args

---

changes.go
changes_test.go
handlers.go

... and return an error that steers towards the change to fix it.
When a user redeploys a bundle into a model where a previous deploy had some failures which were then corrected manually, and they're using --map-machines=existing, they can get an inconsistency between the bundle and model machines such that bundlechanges creates a new machine but then doesn't host any units on it. This causes a panic in `juju deploy`, as seen in https://pad.lv/1773357.
For example, if you have this bundle:
applications:
memcached:
charm: cs:xenial/memcached-21
num_units: 2
to: [0, 1]
machines:
0:
1:
When you deployed it machine 0 failed, so you manually added another unit of memcached (which created machine 2). If you then tried to redeploy the bundle with `--map-machines=existing`, it would see that …

Detect inconsistent bundle-model machine mappings

---

diff.go
diff_test.go
model.go

This compares applications, machines and relations and returns a structure of all of the differences between them.
Features still to come include (in priority order):
* Ignoring num_units differences for subordinate applications
* Comparing series on applications, machines and models
* (Down the line further) comparing resources, storage, devices and endpoint bindings.

Add BuildDiff to compare a bundle and model

---

changes.go
changes_test.go
dependencies.tsv
diff.go
diff_test.go
handlers.go
model.go

Add support for generating the necessary change events for k8s bundles.
For k8s bundles, unit changes and machine changes are omitted. And applications send the num units with the add event, and there's a new scale application change event.

Add support for k8s bundles

---

changes_test.go
handlers.go

Fixes https://bugs.launchpad.net/juju/+bug/1796378
When determining the series for a charm, if non were specified for the application, the charm default was being used (the first declared series in the charm metadata). Instead, we should have been using the bundle default, if any.

Charms should take their series from the bundle if needed

---

changes.go
changes_test.go
dependencies.tsv
handlers.go

This PR introduces a new Change type called `CreateOfferChange`. This new change type will be used for re-creating application offers if defined within the bundle (see https://github.com/juju/charm/pull/277).

Add create offer change

---

changes.go
changes_test.go
dependencies.tsv
handlers.go

This PR ensures that the `CreateOfferChange` supports multiple endpoints for application offers.

Support multiple endpoints for create offer changes

---

changes.go

This change makes the description of create offer in `juju deploy` output a bit cleaner:
e.g. `create offer my-offer using apache2:apache-website,website-cache`

Improve description of CreateOfferChange

---

changes.go
changes_test.go
dependencies.tsv
handlers.go

This PR is part of the work required to support bundles that can specify a per-charm channel preference.
The PR also includes a small drive-by fix to remove an old dependency to charmrepo.v2 which ends up in juju's transient dependency list.

Update AddCharm change type to include the channel

---

changes.go
changes_test.go

The commit moves the params back to each type class, along with
moving the Args() method. The reason for this change is that the
handlers that walk through the types edits the types from the
outside and the params you expect to be created and edited up
front aren't the same ones that are modified later on. So in the
end, only the params of each type class get's changed, not the
ones in changeInfo. Which ultimately means that when it comes
to serialise the results, it ends up being wrong as data is
ends up being missed.
If this library ever get's re-written then a vistor pattern would
do wonders for encaspulation and handling of one's own
responsibilities. In the mean time, the following changes are a
step in the right direction.

Move params and Args() to each type class

---

changes.go
handlers.go

- Local relative paths no longer get parsed by ParseURL. Default to the defaultSeries.
- Handle errors returned by ParseURL to fix panics.

Fix local relative charm and invalid URL panic

---

diff.go
diff_test.go

According to the bundle schema [docs](https://juju.is/docs/bundle-reference), a bundle may omit the endpoint from the relation list. As a result, when diffing against such a bundle, an index out of bounds panic would be generated.
This PR avoids the panic by substituting an empty endpoint. Note that this patch will generate spurious diff entries (see test in https://github.com/juju/bundlechanges/commit/41b62b9db3b1f0b8ac37807b8e2a64d27ab63d6c). The plan is to have juju emit a warning for the missing endpoints and advise the operator to update their local bundle.
Related bug: https://bugs.launchpad.net/juju/+bug/1882573

Substitute empty string for missing relation endpoints when diffing

---

model.go
model_test.go

The following ensure that the applications that we loop through are
deterministic, so that when adding application units we skip correctly
with in the loop.
This is fixing LP #1883645

Adding deterministic processing of bundle machines

---

changes.go
changes_test.go
go.mod
go.sum
handlers.go
model.go

This PR incorporates the `charm` package changes from https://github.com/juju/charm/pull/315 and https://github.com/juju/charm/pull/316 and updates the change logic to include the expose parameters
when emitting expose changes.
One noticeable change in behavior is that prior to this change, we only emitted an expose change **once** when the expose status of an application changes to `true`. Since the operator can now change some of the expose parameters, the change generator will first check whether the controller model shows the app as already exposed and if that's the case it will compare the individual incoming expose parameters to the ones reported by the controller and emit an expose change in case of a mismatch.

Include expose params in expose application change

---

changes.go
changes_test.go
cmd/get-bundle-changes/main.go
diff_test.go
go.mod
go.sum
handlers.go
model.go

Due to the recent design change where expose settings can be specified per endpoint, the changes introduced by #66 had to be revised to adhere to the new design.
Because of these changes, the description for an expose change would now become a multi-line string. To this end, the signature of the `Description` method for the `Change` interface has been modified to return a `[]string` instead so that the caller can appropriately render the description items. This change breaks backwards compatibility so a new (v2.0.0) branch has been created and the package version on master has been bumped to 3.

Tweak payload for expose change parameters

---

diff.go
diff_test.go

The previous implementation used the model structs for the exposed endpoint diff entries which do not include any serialization hints. As a result, the output looks ugly when marshaled into yaml by the juju cli.
To fix this issue, this PR introduces an extra struct `ExposedEndpointDiffEntry` which provides the yaml hints (unfortunately using underscores to match the exposed_endpoints key in the root diff object)

Add yaml serialization hints for ExposedEndpoint diff entries

---

changes.go
changes_test.go
diff.go
diff_test.go

In order to be IPV6-friendly, juju will include both the IPV4 (0.0.0.0/0) and IPV6 (::/0) wildcard CIDRs when generating ingress rules for applications (or individual endpoints) that are exposed to the world.
To this end, this PR revises the description generator for expose changes to include both CIDRs and the diff logic to assume both wildcards are present when diffing against models and/or bundles that indicate an exposed information without any per endpoint expose settings present.

IPV6 friendly expose descriptions and diffs

---

Makefile
changes.go
changes_test.go
cmd/get-bundle-changes/main.go
diff_test.go
go.mod

The following updates the descriptions for all charmhub changes. It
drops the URL schema and revision in favour of plain text.
This makes it easier to the user about what is happening and when
without the understanding or parsing for the given output.
Note: this is a version bump to v4 to prevent v3 users breaking.

Re-write the descriptions

---

Makefile
changes.go
changes_test.go
cmd/get-bundle-changes/main.go
diff.go
diff_test.go
go.mod
go.sum
handlers.go
model.go
model_test.go

The following upgrades the dependencies for charm and charmrepo. These
repos are locked stepped together and should be merged together at some
point.

Upgrade dependencies for charm and charmrepo

---

changes.go
changes_test.go
handlers.go

When adding a charm from charm-hub to juju, we now need to know the
architecture. This works fine for most things, but unfotunately we need
this from the bundle as well. Unluckily the arch constraint is for an
application and we need it for adding charms. The two are separated
(addCharm and addApplication) and addCharm is the first one, so we don't
have the constraints to go look in.
The code ensures that we don't leak the whole series of constraints out
at the addCharm level. Instead we allow the passing in of a parser for
application constraints using the config. If the config doesn't have an
arch it falls back to empty (omitting when empty) and works the way it
did previously. Finding one ensures that we get that information.
Additionally I changed the way the description is …

Expose arch with add charm change

---

changes.go
changes_test.go
handlers.go

When adding a charm from charm-hub to juju, we now need to know the
architecture. This works fine for most things, but unfotunately we need
this from the bundle as well. Unluckily the arch constraint is for an
application and we need it for adding charms. The two are separated
(addCharm and addApplication) and addCharm is the first one, so we don't
have the constraints to go look in.
The code ensures that we don't leak the whole series of constraints out
at the addCharm level. Instead we allow the passing in of a parser for
application constraints using the config. If the config doesn't have an
arch it falls back to empty (omitting when empty) and works the way it
did previously. Finding one ensures that we get that information.
Additionally I changed the way the description is …

Back port add charm architecture

---

changes.go
changes_test.go
go.mod
go.sum
handlers.go
model.go

So if an application has existing architecture or series information
then we should set the constraints for the given application. If a
bundle has constraints and series set then the application should upload
a new charm and register a change.
As each charm is a unique blob we have no way to say grab be all of
these series of things, instead we have to upload one at a time
potentially stopping us from getting what we want if one differs
(heterogeneous applications).
The code is rather simple as we've done all the heavy lifting, the
change is to ensure that the key for the application is unique for every
architecture and series.

Upload application with arch/series constraint

---

go.mod
go.sum

The following just updates the charm dependency so we have a consistent
view of the charm in juju. You need to do this because we check for
errors and different charm dependencies in the same binary can lead to
errors not being matched.

Update charm dependency

---

go.mod
go.sum

This brings in the v9 charm changes.
Again I'll reiterate, all the following libraries should be inside Juju
package, as they're locked to a version release of Juju:
- charm
- charmrepo
- bundlechanges

Update charm and charmrepo deps

---

changes.go
changes_test.go
handlers.go
model.go

Once master was updated to the latest charm and charmrepo dependencies, we can now bring v4 branch into master.
96f5359 (upstream/v4, origin/v4, v4) Merge pull request #79 from SimonRichardson/update-charm-dep
df91c02 Merge pull request #78 from SimonRichardson/add-change-based-on-application-arch
665b333 Merge pull request #77 from SimonRichardson/back-port-add-charm-architecture

Merge V4 into master

---

changes.go
changes_test.go
handlers.go
model.go

This PR enhances the controller model definition to include a list of offers for each application. This change allows us to detect whether an offer already exists or whether it needs to be created from scratch. The package indicates this via a new attribute (`Update`) which has been added to `CreateOfferChangeParams`.

Distinguish between creating and updating offers when calculating changes

---

diff.go
diff_test.go

When applying a bundle diff to a model and a bundle we should also take
into account the bundle series. The bundle series should be taken into
account as that is the same mechanism as Juju takes into account and how
bundle themselves parsing works.
This should make it much more efficient when comparing existing bundles
when series fields are empty and global series is filled.

Handle bundle series

---

changes.go
changes_test.go
handlers.go
model.go

Juju needs to know more about channels that an application can be given
and because of the way addCharm and addApplication is split it becomes
harder to understand the key change.
The code is simple, expose channel in the same way that series is on the
application and push it through the code.
There already exists a test for channels, so modifying that to show the
right thing was easy.

Add application channel

---

changes.go
changes_test.go
handlers.go
handlers_test.go

The following changes updates the revision getter to now pass back the
channel. Updating any code to ensure that we rename any old naming to
the new one.
Unfortunately we have to request the channel before we can check the
equality, previously we checked just the channels. This became a problem
when the existing application had been resolved even if the channel was
empty, yet the bundle was still shown to be empty. Effectively
preventing the deployment of bundles with empty channels. The new unit
tests ensure we get the correct error message based on the content of
the model and the bundle.

Pass channel back when resolving.

---

handlers.go
handlers_test.go

Older controllers ignored channels and so should we when looking at
existing information.
The code just bails out if we're speaking to an older controller.

Handle talking to older controllers
